version: "3.8"

services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sqlserver
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=Pass@word123
    ports:
      - "1433:1433"
    volumes:
      - ./data:/var/opt/mssql/data
    restart: always